services:
  pdf-converter:
    labels:
      - traefik.enable=true
      - traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${PROJECT_NAME}.entrypoints=http
      - traefik.http.routers.${PROJECT_NAME}.rule=Host(`${HOST}`)
      # Auto redirection from http to https
      - traefik.http.routers.${PROJECT_NAME}.middlewares=https-redirect@file
      - traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=https
      - traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${HOST}`)
      - traefik.http.routers.${PROJECT_NAME}-secure.tls=true